[package]
name = "nu_plugin_len"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.84.1" }
nu-protocol = { path = "../nu-protocol", version = "0.84.1" }
